export const Trendingdata = {
  General: {
    topFourHasgtag: ["#istanbul", "#taksim", "#hairtransplant", "#turkiye"],

    topFourHObj: {
      istanbulhtag: "#istanbul",
      ekkanHTag: "#taksim",
      duybeniHtag: "#hairtransplant",
      turkeyHtag: "#turkiye",
    },

    topFourHtagCount: {
      istanbulCount: 432,
      ekkanCount: 150,
      duybeniCount: 78,
      turkeyCount: 195,
    },

    duybeniHtag: [
      "#hairtransplantturkey",
      "#hairtransplantistanbul",
      "#hairtransplantation",
      "#hairtransplantsurgery",
      "#hairtransplantfue",
      "#hairtransplantcenter",
      "#istanbul",
      "#türkiye",
      "#hairtransplantresults",
      "#dhi",
      "#sercanaslanhairclinic",
      "#clienttestimonial",
      "#vanessahairnevatr",
      "#thorhairclinic",
      "#beardtransplant",
      "#besthairtransplantclinics",
      "#shifthairtransplantturkey",
      "#plasticsurgeryturkey",
      "#dentalaesthetic",
      "#hairtransplantclinic",
    ],

    ekkanHTag: [
      "#izmirbomba",
      "#taksimexplosion",
      "#istiklalstreet",
      "#bomb",
      "#terrorism",
      "#police",
      "#livingini̇stanbul",
      "#iyigeceler",
      "#turkiye",
      "#taksimsquare",
      "#istiklal",
      "#istambul",
      "#explosion",
      "#patlama",
      "#stoltenberg",
      "#security",
      "#antiterror",
      "#saynototerrorism",
      "#msb",
      "#espressolab",
    ],

    istanbulhtag: [
      "#turkey",
      "#hairtransplant",
      "#nftcommunity",
      "#suleymaniyemosque",
      "#turkishcitizenship",
      "#blue musque",
      "#hairtranspalntinturkey",
      "#turkish",
      "#modernartist",
      "#streetphotography",
      "#realestateistanbul",
      "#beauty",
      "#kemerburgaz",
      "#turkishdelights",
      "#taksim",
      "#turkeyteeth",
      "#ayurveda",
      "#investinturkey",
      "#traveling",
      "#islamophobia",
    ],

    turkeyHtag: [
      "#economic",
      "#studyinturkey",
      "#turkishairlines",
      "#azerbaijan",
      "#instanbul",
      "#cooperation",
      "#protocol",
      "#citizenship",
      "#emissions",
      "#refugees",
      "#galatakulesi",
      "#knowledgeislight",
      "#jumakhutba",
      "#ikfeuwkcqb",
      "#keşfet",
      "#receptayyiperdogan",
      "#telethonbyimrankhan",
      "#twitchstreamer",
      "#ekonomi",
      "#newprofilepic",
    ],

    topTwentyHtag: [
      "#turkey",
      "#hairtransplant",
      "#nftcommunity",
      "#suleymaniyemosque",
      "#turkishcitizenship",
      "#izmirbomba",
      "#taksimexplosion",
      "#istiklalstreet",
      "#bomb",
      "#terrorism",
      "#hairtransplantturkey",
      "#hairtransplantistanbul",
      "#hairtransplantation",
      "#hairtransplantsurgery",
      "#hairtransplantfue",
      "#economic",
      "#studyinturkey",
      "#turkishairlines",
      "#azerbaijan",
      "#instanbul",
    ],
  },

  Traffic: {
    topFourHasgtag: ["#traffic", "#transportation", "#istanbul", "#turkiye"],

    topFourHtagCount: {
      coachingCount: 200,
      leadershipCount: 117,
      actCount: 112,
      inspireCount: 104,
    },

    topFourHObj: {
      istanbulhtag: "#traffic",
      ekkanHTag: "#transportation",
      duybeniHtag: "#istanbul",
      turkeyHtag: "#turkiye",
    },

    istanbulhtag: [
      "#istanbul",
      "#mytimeisvaluable",
      "#trafficlights",
      "#turkeyrealestate",
      "#realestate",
      "#vipproperty",
      "#turkishcitizenship",
      "#investment",
      "#attack",
      "#gunman",
      "#murder",
      "#ahrefs",
      "#ahrefs",
      "#semrush",
      "#data",
      "#suez",
      "#canal",
      "#chip",
      "#vehicles",
      "#transport",
    ],

    ekkanHTag: [
      "#lojistik",
      "#slg",
      "#digitalsolutions",
      "#logisticsmanagement",
      "#logistics",
      "#transport",
      "#trucking",
      "#travel",
      "#freight",
      "#shipping",
      "#cargo",
      "#trucks",
      "#truck",
      "#supplychain",
      "#truckdriver",
      "#business",
      "#delivery",
      "#bus",
      "#photography",
      "#car",
    ],

    duybeniHtag: [
      "#turkey",
      "#hairtransplant",
      "#nftcommunity",
      "#suleymaniyemosque",
      "#turkishcitizenship",
      "#blue musque",
      "#hairtranspalntinturkey",
      "#turkish",
      "#modernartist",
      "#streetphotography",
      "#realestateistanbul",
      "#beauty",
      "#kemerburgaz",
      "#turkishdelights",
      "#taksim",
      "#turkeyteeth",
      "#ayurveda",
      "#investinturkey",
      "#traveling",
      "#islamophobia",
    ],

    turkeyHtag: [
      "#economic",
      "#studyinturkey",
      "#turkishairlines",
      "#azerbaijan",
      "#instanbul",
      "#cooperation",
      "#protocol",
      "#citizenship",
      "#emissions",
      "#refugees",
      "#galatakulesi",
      "#knowledgeislight",
      "#jumakhutba",
      "#ikfeuwkcqb",
      "#keşfet",
      "#receptayyiperdogan",
      "#telethonbyimrankhan",
      "#twitchstreamer",
      "#ekonomi",
      "#newprofilepic",
    ],

    topTwentyHtag: [
      "#istanbul",
      "#mytimeisvaluable",
      "#trafficlights",
      "#turkeyrealestate",
      "#realestate",
      "#vipproperty",
      "#turkishcitizenship",
      "#investment",
      "#attack",
      "#gunman",
      "#turkey",
      "#hairtransplant",
      "#nftcommunity",
      "#suleymaniyemosque",
      "#turkishcitizenship",
      "#izmirbomba",
      "#economic",
      "#studyinturkey",
      "#turkishairlines",
      "#azerbaijan",
    ],
  },

  Government: {
    topFourHasgtag: ["#bomba", "#leadership", "#taksim", "#blast"],

    topFourHtagCount: {
      coachingCount: 200,
      leadershipCount: 117,
      actCount: 112,
      inspireCount: 104,
    },
    topFourHObj: {
      istanbulhtag: "#bomba",
      ekkanHTag: "#leadership",
      duybeniHtag: "#taksim",
      turkeyHtag: "#blast",
    },

    istanbulhtag: [
      "#istanbul",
      "#turkey",
      "#turkiye",
      "#taksim",
      "#pkk",
      "#patlama",
      "#terorulanetliyoruz",
      "#pakistan",
      "#bombattack",
      "#izmirbomba",
      "#espressolab",
      "#robloxdev",
      "#roblox",
      "#ecchi",
      "#adivasi",
      "#dank",
      "#indiedev",
      "#gamedev",
      "#systematicreview",
      "#illustration",
    ],

    ekkanHTag: [
      "#technology",
      "#cio",
      "#digitalemployeeexperience",
      "#business",
      "#artificialintelligence",
      "#machinelearning",
      "#automation",
      "#digitaltransformation",
      "#productivity",
      "#effectiveness",
      "#teams",
      "#selfdevelopment",
      "#professionaldevelopment",
      "#emotional",
      "#resilience",
      "#enhance",
      "#spirit",
      "#focus",
      "#blessing",
      "#marketing",
    ],

    duybeniHtag: [
      "#security",
      "#msb",
      "#antiterror",
      "#taksimpatlama",
      "#saynototerrorism",
      "#izmirbomba",
      "#espressolab",
      "#taksim",
      "#robloxdev",
      "#roblox",
      "#ecchi",
      "#adivasi",
      "#dank",
      "#indiedev",
      "#gamedev",
      "#systematicreview",
      "#illustration",
      "#100daysofcode",
      "#nodejs",
      "#artificialintelligence",
    ],

    turkeyHtag: [
      "#ypg",
      "#pkk",
      "#istanbuls",
      "#suspects",
      "#bomb",
      "#emmanuelmacron",
      "#polish",
      "#missile",
      "#nato",
      "#turkey",
      "#taksimpatlama",
      "#antonyblinken",
      "#russia",
      "#blast",
      "#poland",
      "#biden",
      "#us",
      "#saynototerrorism",
      "#izmirbomba",
      "#espressolab",
    ],

    topTwentyHtag: [
      "#istanbul",
      "#turkey",
      "#turkiye",
      "#taksim",
      "#pkk",
      "#technology",
      "#cio",
      "#digitalemployeeexperience",
      "#business",
      "#artificialintelligence",
      "#security",
      "#msb",
      "#antiterror",
      "#taksimpatlama",
      "#saynototerrorism",
      "#ypg",
      "#pkk",
      "#istanbuls",
      "#suspects",
      "#bomb",
    ],
  },

  Health: {
    topFourHasgtag: ["#hairtransplant", "#health", "#medical", "#fue"],

    topFourHtagCount: {
      coachingCount: 200,
      leadershipCount: 117,
      actCount: 112,
      inspireCount: 104,
    },
    topFourHObj: {
      istanbulhtag: "#hairtransplant",
      ekkanHTag: "#health",
      duybeniHtag: "#medical",
      turkeyHtag: "#fue",
    },

    istanbulhtag: [
      "#hairtransplantturkey",
      "#hairtransplantistanbul",
      "#hairtransplantation",
      "#hairtransplantsurgery",
      "#hairtransplantfue",
      "#hairtransplantcenter",
      "#istanbul",
      "#türkiye",
      "#hairtransplantresults",
      "#sercanaslanhairclinic",
      "#dhi",
      "#clienttestimonial",
      "#vanessahairnevatr",
      "#thorhairclinic",
      "#beardtransplant",
      "#besthairtransplantclinicsinistanbul",
      "#shifthairtransplantturkeyreviews",
      "#plasticsurgeryturkey",
      "#dentalaesthetic",
      "#hairtransplantclinic",
    ],

    ekkanHTag: [
      "#sherunsforever",
      "#love",
      "#happyhour",
      "#memyselfandi",
      "#fitness",
      "#healthylifestyle",
      "#wellness",
      "#healthy",
      "#motivation",
      "#workout",
      "#gym",
      "#love",
      "#lifestyle",
      "#fit",
      "#fitnessmotivation",
      "#training",
      "#nutrition",
      "#exercise",
      "#psychology",
      "#psychiatry",
    ],

    duybeniHtag: [
      "#bagcilarsafakglobal",
      "#health",
      "#healthcare",
      "#doctors",
      "#patientcare",
      "#medicare",
      "#urgentcare",
      "#globalhealth",
      "#wellness",
      "#brazilianbuttlift",
      "#bbl",
      "#buttlife",
      "#medica2022",
      "#medica",
      "#dusseldorf",
      "#germany",
      "#lifesciences",
      "#internationalfair",
      "#diagnostics",
      "#whozyme",
    ],

    turkeyHtag: [
      "#hair",
      "#hairtransplant",
      "#hairtransformation",
      "#dhi",
      "#fuetecnigue",
      "#hairtransplantturkey",
      "#hairtransplantistanbul",
      "#landofhair",
      "#hairtransplantbeforeafter",
      "#instagram",
      "#saçekimi",
      "#transplantecapilar",
      "#hairrestoration",
      "#fuehairtransplant",
      "#beardtransplant",
      "#besthairtransplantclinicsinistanbul",
      "#shifthairtransplantturkeyreviews",
      "#plasticsurgeryturkey",
      "#dentalaesthetic",
      "#hairtransplantclinic",
    ],

    topTwentyHtag: [
      "      #hairtransplantturkey",
      "      #hairtransplantistanbul",
      "      #hairtransplantation",
      " #hairtransplantsurgery",
      "#hairtransplantfue",
      " #sherunsforever",
      "      #love",
      "  #happyhour",
      "  #memyselfandi",
      "#fitness",
      "  #bagcilarsafakglobal",
      "#health",
      "  #healthcare",
      " #doctors",
      " #patientcare",
      "#hair",
      " #hairtransplant",
      "   #hairtransformation",
      "  #dhi",
      "#fuetecnigue",
    ],
  },

  Education: {
    topFourHasgtag: [
      "#education",
      "#Information",
      "#Learning",
      "#studentsuccess",
    ],

    topFourHtagCount: {
      coachingCount: 200,
      leadershipCount: 117,
      actCount: 112,
      inspireCount: 104,
    },

    topFourHObj: {
      istanbulhtag: "#education",
      ekkanHTag: "#Information",
      duybeniHtag: "#Learning",
      turkeyHtag: "#studentsuccess",
    },

    istanbulhtag: [
      "#univechain",
      "#blockchain",
      "#career",
      "#web3community",
      "#maxlogic",
      "#mavigard",
      "#firealarm",
      "#firealarmsystem",
      "#gasalarmsystems",
      "#webinar",
      "#freewebinar",
      "#seminar",
      "#onlinewebinar",
      "#onlineeducation",
      "#adventure",
      "#gameindustry",
      "#indie",
      "#incubation",
      "#gamedesign",
      "#gamedevelopment",
    ],

    ekkanHTag: [
      "#orthopedicsurgery",
      "#cosmeticlimblengthening",
      "#leglengtheningsurgery",
      "#preciceimplant",
      "#bone",
      "#xray",
      "#radiograph",
      "#ircica",
      "#islamic",
      "#conference",
      "#ministers",
      "#demonstrations",
      "#demonstrators",
      "#children",
      "#digitaltransformation",
      "#studentsuccess",
      "#whereeverythingconnects",
      "#edtech",
      "#elearning",
      "#value",
    ],

    duybeniHtag: [
      "#perculus",
      "#onlineclassrooms",
      "#liveclassrooms",
      "#experience",
      "#digitaltraining",
      "#elearning",
      "#whereeverythingconnects",
      "#experience",
      "#books",
      "#university",
      "#college",
      "#school",
      "#we",
      "#webinar",
      "#seminar",
      "#onlineeducation",
      "#cousre",
      "#lesson",
      "#children",
      "#value",
    ],

    turkeyHtag: [
      "#digitaltransformation",
      "#whereeverythingconnects",
      "#edtech",
      "#elearning",
      "#freewebinar",
      "#seminar",
      "#onlinewebinar",
      "#onlineeducation",
      "#adventure",
      "#books",
      "#university",
      "#college",
      "#school",
      "#we",
      "#webinar",
      "#lesson",
      "#children",
      "#value",
      "#edtech",
      "#univechain",
    ],

    topTwentyHtag: [
      "#univechain",
      "#blockchain",
      "#career",
      "#web3community",
      "#maxlogic",
      "#orthopedicsurgery",
      "#cosmeticlimblengthening",
      "#leglengtheningsurgery",
      "#preciceimplant",
      "#bone",
      "#perculus",
      "#onlineclassrooms",
      "#liveclassrooms",
      "#experience",
      "#digitaltraining",
      "#digitaltransformation",
      "#whereeverythingconnects",
      "#edtech",
      "#elearning",
      "#freewebinar",
    ],
  },

  Lifestyle: {
    topFourHasgtag: [
      "#fashion",
      "#healthylifestyle",
      "#beauty",
      "#photography",
    ],

    topFourHtagCount: {
      coachingCount: 200,
      leadershipCount: 117,
      actCount: 112,
      inspireCount: 104,
    },
    topFourHObj: {
      istanbulhtag: "#fashion",
      ekkanHTag: "#healthylifestyle",
      duybeniHtag: "#beauty",
      turkeyHtag: "#photography",
    },

    istanbulhtag: [
      "#buttons",
      "#apparelbuttons",
      "#clothingbrand",
      "#garmentmanufacturing",
      "#fashionstyle",
      "#moda",
      "#apparelbrand",
      "#silver",
      "#earrings",
      "#women",
      "#flower",
      "#tiny",
      "#studearrings",
      "#handmade",
      "#handcrafted",
      "#business",
      "#jewelry",
      "#jewellery",
      "#wholesale",
      "#trendy",
    ],

    ekkanHTag: [
      "#health",
      "#o2care",
      "#healthcareconsultancy",
      "#medical",
      "#hospitalconstruction",
      "#gym",
      "#love",
      "#lifestyle",
      "#fit",
      "#fitnessmotivation",
      "#training",
      "#nutrition",
      "#exercise",
      "#psychology",
      "#psychiatry",
      "#wellness",
      "#healthy",
      "#motivation",
      "#workout",
      "#fitness",
    ],

    duybeniHtag: [
      "#electric",
      "#dognail",
      "#clipper",
      "#petshop",
      "#nailart",
      "#fromscratch",
      "#new",
      "#italian",
      "#limitedseries",
      "#italiano",
      "#italiacultures",
      "#tiny",
      "#studearrings",
      "#handmade",
      "#handcrafted",
      "#business",
      "#jewelry",
      "#jewellery",
      "#wholesale",
      "#trendy",
    ],

    turkeyHtag: [
      "#superbike",
      "#bikeswithoutlimits",
      "#motorrad",
      "#kask",
      "#bikerkings",
      "#rider",
      "#sportbike",
      "#yamaha",
      "#honda",
      "#bikersofinstagram",
      "#bikelife",
      "#studio",
      "#instashoot",
      "#lightroomtutorial",
      "#god",
      "#photo",
      "#siteglobal",
      "#imex2022",
      "#liveevents",
      "#ibtmworld",
    ],

    topTwentyHtag: [
      "#buttons",
      "#apparelbuttons",
      "#clothingbrand",
      "#garmentmanufacturing",
      "#fashionstyle",
      "#health",
      "#o2care",
      "#healthcareconsultancy",
      "#medical",
      "#hospitalconstruction",
      "#electric",
      "#dognail",
      "#clipper",
      "#petshop",
      "#nailart",
      "#superbike",
      "#bikeswithoutlimits",
      "#motorrad",
      "#kask",
      "#bikerkings",
    ],
  },

  Economics: {
    topFourHasgtag: ["#inflation", "#economy", "#augmentedreality", "#economy"],

    topFourHtagCount: {
      coachingCount: 200,
      leadershipCount: 117,
      actCount: 112,
      inspireCount: 104,
    },
    topFourHObj: {
      istanbulhtag: "#inflation",
      ekkanHTag: "#economy",
      duybeniHtag: "#augmentedreality",
      turkeyHtag: "#economy",
    },

    istanbulhtag: [
      "#prices",
      "#instability",
      "#economic",
      "#political",
      "#economy",
      "#interestrates",
      "#resigned",
      "#rises",
      "#statebankofvietnam",
      "#uk",
      "#australia",
      "#britain",
      "#unitedkingdom",
      "#liztruss",
      "#outlook",
      "moodys",
      "#britains",
      "#vietnam",
      "#finance",
      "#industry",
    ],

    ekkanHTag: [
      "#gdp",
      "#industry",
      "#finance",
      "#growth",
      "#gamefi",
      "#youtube",
      "#blockchain",
      "#blockchaingaming",
      "#nft",
      "#web3",
      "#binance",
      "#btc",
      "#ethereum",
      "#eth",
      "#fuzul",
      "#fuzulev",
      "#fuzularaba",
      "#titaniumeconomy",
      "#books",
      "#mckinsey",
    ],

    duybeniHtag: [
      "#bigtech",
      "#immersivetechnology",
      "#technology",
      "#intellectualproperty",
      "#physicalworld",
      "#intellectualpropertyrights",
      "#legal",
      "#virtual",
      "#startup",
      "#oculusquest",
      "#virtualrealityworld",
      "#education",
      "#arcore",
      "#extendedreality",
      "#vrgaming",
      "#machinelearning",
      "#games",
      "#digital",
      "#mr",
      "#gosnapshot",
    ],

    turkeyHtag: [
      "#skorea",
      "#southkorea",
      "#korea",
      "#housing",
      "#creditrisk",
      "#mortgage",
      "#interestrates",
      "#seoul",
      "#building",
      "#residential",
      "#business",
      "#realtorlife",
      "#luxury",
      "#interiordesign",
      "#newlisting",
      "#homeforsale",
      "#openhouse",
      "#apartments",
      "#homeinspection",
      "#rent",
    ],

    topTwentyHtag: [
      "#prices",
      "#instability",
      "#economic",
      "#political",
      "#economy",
      "#gdp",
      "#industry",
      "#finance",
      "#growth",
      "#gamefi",
      "#bigtech",
      "#immersivetechnology",
      "#technology",
      "#intellectualproperty",
      "#physicalworld",
      "#skorea",
      "#southkorea",
      "#korea",
      "#housing",
      "#creditrisk",
    ],
  },

  Culture: {
    topFourHasgtag: ["#art", "#nft", "#music", "#architecture"],

    topFourHtagCount: {
      coachingCount: 200,
      leadershipCount: 117,
      actCount: 112,
      inspireCount: 104,
    },
    topFourHObj: {
      istanbulhtag: "#art",
      ekkanHTag: "#nft",
      duybeniHtag: "#music",
      turkeyHtag: "#architecture",
    },

    istanbulhtag: [
      "#nft",
      "#painting",
      "#artgallery",
      "#artist",
      "#erasmus",
      "#monument",
      "#nftartwork",
      "#procreate",
      "#procreateart",
      "#sketch",
      "#sketchart",
      "#skateboarding",
      "#sk8",
      "#sk8boarder",
      "#web3",
      "#drawingpen",
      "#wise",
      "#women",
      "#potritdrawing",
      "#decorativeart",
    ],

    ekkanHTag: [
      "#nftcommunity",
      "#womensart",
      "#nfts",
      "#art",
      "#monument",
      "#nftartwork",
      "#sketchart",
      "#skateboarding",
      "#sk8",
      "#sk8boarder",
      "#web3",
      "#cryptoart",
      "#raredigitalart",
      "#ethereum",
      "#nftclub",
      "#cryptoartist",
      "#blockchain",
      "#animation",
      "#rocketdudeart",
      "#nftspacerocket",
    ],

    duybeniHtag: [
      "#intotheblack",
      "#jeffblackburn",
      "#neilyoung",
      "#heyheymymy",
      "#fire",
      "#night",
      "#nature",
      "#vote",
      "#indiemusic",
      "#spotifyplaylist",
      "#ellafitzgerald",
      "#jazzfestival",
      "#instrument",
      "#flute",
      "#soothing",
      "#refresh",
      "#vibe",
      "#fav",
      "#soft",
      "#love",
    ],

    turkeyHtag: [
      "#building",
      "#business",
      "#company",
      "#construction",
      "#corporate",
      "#design",
      "#engineering",
      "#garden",
      "#house",
      "#landscape",
      "#lawn",
      "#maintenance",
      "#repair",
      "#roof",
      "#roofing",
      "#exteriordesign",
      "#roofrepair",
      "#roofingservices",
      "#boutiquehotel",
      "#roomdecor",
    ],

    topTwentyHtag: [
      "#nft",
      "#painting",
      "#artgallery",
      "#artist",
      "#erasmus",
      "#nftcommunity",
      "#womensart",
      "#nfts",
      "#art",
      "#monument",
      "#intotheblack",
      "#jeffblackburn",
      "#neilyoung",
      "#heyheymymy",
      "#fire",
      "#building",
      "#business",
      "#company",
      "#construction",
      "#corporate",
    ],
  },
};
