export const data = {
  General: [
    {
      Username: "riyazulkhaliq",
      MediaImpact: "5137528",
      Followers: "2768",
      Category: "General",
    },
    {
      Username: "cover_up8d",
      MediaImpact: "5113897",
      Followers: "787",
      Category: "General",
    },
    {
      Username: "hairBurak",
      MediaImpact: "3567532",
      Followers: "5119",
      Category: "General",
    },
    {
      Username: "MariaRamosUK",
      MediaImpact: "1132977",
      Followers: "16599",
      Category: "General",
    },
    {
      Username: "fatihaydin_TC",
      MediaImpact: "594878",
      Followers: "12048",
      Category: "General",
    },
    {
      Username: "RenaNetjes",
      MediaImpact: "431805",
      Followers: "26427",
      Category: "General",
    },
    {
      Username: "businessturkey",
      MediaImpact: "393298",
      Followers: "1055",
      Category: "General",
    },
    {
      Username: "loosemoose97",
      MediaImpact: "392099",
      Followers: "918",
      Category: "General",
    },
    {
      Username: "mozsimsek",
      MediaImpact: "377000",
      Followers: "7772",
      Category: "General",
    },
    {
      Username: "sagistgrup",
      MediaImpact: "368852",
      Followers: "2560",
      Category: "General",
    },
    {
      Username: "mikelayestaran",
      MediaImpact: "336125",
      Followers: "180860",
      Category: "General",
    },
    {
      Username: "arjenuijterlind",
      MediaImpact: "294076",
      Followers: "5595",
      Category: "General",
    },
    {
      Username: "OneNationTravel",
      MediaImpact: "284718",
      Followers: "14570",
      Category: "General",
    },
    {
      Username: "HDNER",
      MediaImpact: "276613",
      Followers: "276536",
      Category: "General",
    },
    {
      Username: "metesohtaoglu",
      MediaImpact: "274430",
      Followers: "69699",
      Category: "General",
    },
    {
      Username: "MoonAlev",
      MediaImpact: "253373",
      Followers: "1784",
      Category: "General",
    },
    {
      Username: "LorenaLavinia",
      MediaImpact: "251760",
      Followers: "170",
      Category: "General",
    },
    {
      Username: "CaKizil",
      MediaImpact: "233651",
      Followers: "208422",
      Category: "General",
    },
    {
      Username: "atahanselekoglu",
      MediaImpact: "224187",
      Followers: "404",
      Category: "General",
    },
    {
      Username: "ahb651",
      MediaImpact: "218214",
      Followers: "3377",
      Category: "General",
    },
    {
      Username: "minemanapturel",
      MediaImpact: "218169",
      Followers: "3105",
      Category: "General",
    },
    {
      Username: "MELEK7452",
      MediaImpact: "211504",
      Followers: "4898",
      Category: "General",
    },
    {
      Username: "Safa_Zakholy",
      MediaImpact: "196989",
      Followers: "4647",
      Category: "General",
    },
    {
      Username: "kristin_violet1",
      MediaImpact: "192507",
      Followers: "118",
      Category: "General",
    },
    {
      Username: "KeremGarip5",
      MediaImpact: "186423",
      Followers: "2642",
      Category: "General",
    },
    {
      Username: "ze7nep",
      MediaImpact: "185889",
      Followers: "847",
      Category: "General",
    },
    {
      Username: "TRTWorldNow",
      MediaImpact: "183274",
      Followers: "183253",
      Category: "General",
    },
    {
      Username: "VialliChelseaFC",
      MediaImpact: "174756",
      Followers: "16680",
      Category: "General",
    },
    {
      Username: "sukru66guven",
      MediaImpact: "170353",
      Followers: "5541",
      Category: "General",
    },
    {
      Username: "_duybeniekkan",
      MediaImpact: "168644",
      Followers: "138",
      Category: "General",
    },
    {
      Username: "AConfusedLamb",
      MediaImpact: "155816",
      Followers: "4505",
      Category: "General",
    },
    {
      Username: "RobinAdamsZA",
      MediaImpact: "145934",
      Followers: "15812",
      Category: "General",
    },
    {
      Username: "Saida_Zahidova",
      MediaImpact: "138774",
      Followers: "5510",
      Category: "General",
    },
    {
      Username: "anilaali",
      MediaImpact: "138700",
      Followers: "21814",
      Category: "General",
    },
    {
      Username: "imamoglu_int",
      MediaImpact: "134078",
      Followers: "132157",
      Category: "General",
    },
    {
      Username: "ikaveri",
      MediaImpact: "129807",
      Followers: "67875",
      Category: "General",
    },
    {
      Username: "Mounzawi",
      MediaImpact: "129217",
      Followers: "217",
      Category: "General",
    },
    {
      Username: "AYCEMSUPREMACY",
      MediaImpact: "126814",
      Followers: "2040",
      Category: "General",
    },
    {
      Username: "Djyeo_coffee",
      MediaImpact: "124875",
      Followers: "4711",
      Category: "General",
    },
    {
      Username: "zaferkarabalik",
      MediaImpact: "122139",
      Followers: "33456",
      Category: "General",
    },
    {
      Username: "EKrkoglu",
      MediaImpact: "122041",
      Followers: "185",
      Category: "General",
    },
    {
      Username: "BerrakBiz",
      MediaImpact: "120883",
      Followers: "6934",
      Category: "General",
    },
    {
      Username: "Map_Addict",
      MediaImpact: "119344",
      Followers: "2179",
      Category: "General",
    },
    {
      Username: "DarleyNewman",
      MediaImpact: "119210",
      Followers: "20728",
      Category: "General",
    },
    {
      Username: "MejaFoss",
      MediaImpact: "116282",
      Followers: "11493",
      Category: "General",
    },
    {
      Username: "hansvantelling",
      MediaImpact: "112816",
      Followers: "68062",
      Category: "General",
    },
    {
      Username: "tugcebabaeren",
      MediaImpact: "108564",
      Followers: "1605",
      Category: "General",
    },
    {
      Username: "Mardounyeh",
      MediaImpact: "107730",
      Followers: "112",
      Category: "General",
    },
    {
      Username: "izharnephrol",
      MediaImpact: "107247",
      Followers: "1015",
      Category: "General",
    },
    {
      Username: "HappinessPatrol",
      MediaImpact: "106650",
      Followers: "1476",
      Category: "General",
    },
    {
      Username: "melisa_reyhan",
      MediaImpact: "103740",
      Followers: "4380",
      Category: "General",
    },
    {
      Username: "AbangOmar",
      MediaImpact: "103428",
      Followers: "2963",
      Category: "General",
    },
    {
      Username: "NabellaAnuar",
      MediaImpact: "102968",
      Followers: "96924",
      Category: "General",
    },
    {
      Username: "AbdulBillowAli",
      MediaImpact: "97881",
      Followers: "60665",
      Category: "General",
    },
    {
      Username: "sequencerider",
      MediaImpact: "96509",
      Followers: "476",
      Category: "General",
    },
    {
      Username: "bassil_taleb",
      MediaImpact: "93965",
      Followers: "1473",
      Category: "General",
    },
    {
      Username: "maryyasmine",
      MediaImpact: "90922",
      Followers: "6227",
      Category: "General",
    },
    {
      Username: "Jzcheniah",
      MediaImpact: "86646",
      Followers: "150",
      Category: "General",
    },
    {
      Username: "UncleLoo",
      MediaImpact: "86566",
      Followers: "1174",
      Category: "General",
    },
    {
      Username: "krista_slade",
      MediaImpact: "85250",
      Followers: "1083",
      Category: "General",
    },
    {
      Username: "Ernesthernand15",
      MediaImpact: "84633",
      Followers: "3063",
      Category: "General",
    },
    {
      Username: "ferhatcekin",
      MediaImpact: "81987",
      Followers: "943",
      Category: "General",
    },
    {
      Username: "SezinOney",
      MediaImpact: "78610",
      Followers: "52420",
      Category: "General",
    },
    {
      Username: "imartinstrecker",
      MediaImpact: "76080",
      Followers: "771",
      Category: "General",
    },
    {
      Username: "erturkvarol",
      MediaImpact: "75713",
      Followers: "394",
      Category: "General",
    },
    {
      Username: "TheTokyoDerek",
      MediaImpact: "74772",
      Followers: "797",
      Category: "General",
    },
    {
      Username: "MeaganWristen",
      MediaImpact: "73043",
      Followers: "46126",
      Category: "General",
    },
    {
      Username: "barryDstocker",
      MediaImpact: "71842",
      Followers: "1191",
      Category: "General",
    },
    {
      Username: "EsraKarahindiba",
      MediaImpact: "71753",
      Followers: "24547",
      Category: "General",
    },
    {
      Username: "enginguneysu",
      MediaImpact: "71170",
      Followers: "3120",
      Category: "General",
    },
    {
      Username: "lauxdby",
      MediaImpact: "70547",
      Followers: "1192",
      Category: "General",
    },
    {
      Username: "iamhuraira",
      MediaImpact: "70367",
      Followers: "44",
      Category: "General",
    },
    {
      Username: "vijivenkatesh",
      MediaImpact: "70252",
      Followers: "9559",
      Category: "General",
    },
    {
      Username: "LunaSafwan",
      MediaImpact: "65054",
      Followers: "29497",
      Category: "General",
    },
    {
      Username: "opheligarcia",
      MediaImpact: "64744",
      Followers: "1710",
      Category: "General",
    },
    {
      Username: "kardelenyarli",
      MediaImpact: "60178",
      Followers: "17627",
      Category: "General",
    },
    {
      Username: "Sirisakc",
      MediaImpact: "59954",
      Followers: "979",
      Category: "General",
    },
    {
      Username: "sonnurbabayigit",
      MediaImpact: "58540",
      Followers: "279",
      Category: "General",
    },
    {
      Username: "mustafacopur",
      MediaImpact: "58284",
      Followers: "1604",
      Category: "General",
    },
    {
      Username: "Iam_Grateful_xo",
      MediaImpact: "58028",
      Followers: "3452",
      Category: "General",
    },
    {
      Username: "KemalogluOz",
      MediaImpact: "57551",
      Followers: "8556",
      Category: "General",
    },
    {
      Username: "KidCon",
      MediaImpact: "55516",
      Followers: "759",
      Category: "General",
    },
    {
      Username: "maryanntheresa",
      MediaImpact: "55254",
      Followers: "1776",
      Category: "General",
    },
    {
      Username: "shifthairtrans",
      MediaImpact: "54311",
      Followers: "836",
      Category: "General",
    },
    {
      Username: "DGPhotography9",
      MediaImpact: "53968",
      Followers: "1896",
      Category: "General",
    },
    {
      Username: "Daniel_Miller8",
      MediaImpact: "52333",
      Followers: "7441",
      Category: "General",
    },
    {
      Username: "itsawais85",
      MediaImpact: "50757",
      Followers: "503",
      Category: "General",
    },
    {
      Username: "jlo_said",
      MediaImpact: "49811",
      Followers: "6813",
      Category: "General",
    },
    {
      Username: "astro_ash_",
      MediaImpact: "49613",
      Followers: "801",
      Category: "General",
    },
    {
      Username: "cjaythecreator",
      MediaImpact: "49574",
      Followers: "2482",
      Category: "General",
    },
    {
      Username: "CommsCraig",
      MediaImpact: "45529",
      Followers: "20341",
      Category: "General",
    },
    {
      Username: "aliboomaye",
      MediaImpact: "45240",
      Followers: "7753",
      Category: "General",
    },
    {
      Username: "alihuseyinoglu",
      MediaImpact: "43981",
      Followers: "2872",
      Category: "General",
    },
    {
      Username: "MightyFineCopy_",
      MediaImpact: "43693",
      Followers: "4351",
      Category: "General",
    },
    {
      Username: "fevzibulganHZK",
      MediaImpact: "42790",
      Followers: "24680",
      Category: "General",
    },
    {
      Username: "FezaRemziMD",
      MediaImpact: "41334",
      Followers: "5556",
      Category: "General",
    },
    {
      Username: "AyhanKaya14",
      MediaImpact: "41073",
      Followers: "5786",
      Category: "General",
    },
    {
      Username: "nevitdilmen",
      MediaImpact: "40740",
      Followers: "1322",
      Category: "General",
    },
    {
      Username: "jiggaholic1",
      MediaImpact: "40582",
      Followers: "2195",
      Category: "General",
    },
    {
      Username: "PrisyncCom",
      MediaImpact: "39895",
      Followers: "2390",
      Category: "General",
    },
    {
      Username: "alifnomad",
      MediaImpact: "39736",
      Followers: "703",
      Category: "General",
    },
    {
      Username: "HSYNYLMZ",
      MediaImpact: "38449",
      Followers: "2890",
      Category: "General",
    },
    {
      Username: "scorpioblr1968",
      MediaImpact: "37970",
      Followers: "440",
      Category: "General",
    },
    {
      Username: "estern53",
      MediaImpact: "36830",
      Followers: "131",
      Category: "General",
    },
    {
      Username: "gabeysena",
      MediaImpact: "36414",
      Followers: "458",
      Category: "General",
    },
    {
      Username: "Kaan01234",
      MediaImpact: "36400",
      Followers: "232",
      Category: "General",
    },
    {
      Username: "anews",
      MediaImpact: "35694",
      Followers: "35334",
      Category: "General",
    },
    {
      Username: "SSB1903",
      MediaImpact: "35285",
      Followers: "486",
      Category: "General",
    },
    {
      Username: "soyuerf",
      MediaImpact: "34536",
      Followers: "1278",
      Category: "General",
    },
    {
      Username: "Fernando1Angulo",
      MediaImpact: "34490",
      Followers: "12932",
      Category: "General",
    },
    {
      Username: "reemosama",
      MediaImpact: "33659",
      Followers: "1102",
      Category: "General",
    },
    {
      Username: "faribanawa",
      MediaImpact: "33635",
      Followers: "6119",
      Category: "General",
    },
    {
      Username: "ShoaibReema",
      MediaImpact: "33534",
      Followers: "665",
      Category: "General",
    },
    {
      Username: "farah912",
      MediaImpact: "33401",
      Followers: "288",
      Category: "General",
    },
    {
      Username: "EceYenice_",
      MediaImpact: "33218",
      Followers: "126",
      Category: "General",
    },
    {
      Username: "cijohnstone23",
      MediaImpact: "32817",
      Followers: "273",
      Category: "General",
    },
    {
      Username: "TedToToe",
      MediaImpact: "32765",
      Followers: "1016",
      Category: "General",
    },
    {
      Username: "KenanPoleo",
      MediaImpact: "32693",
      Followers: "25992",
      Category: "General",
    },
    {
      Username: "KirkhamTravel",
      MediaImpact: "32508",
      Followers: "694",
      Category: "General",
    },
    {
      Username: "KorayGubur",
      MediaImpact: "31722",
      Followers: "13870",
      Category: "General",
    },
    {
      Username: "FulyaOzerkan",
      MediaImpact: "31267",
      Followers: "5238",
      Category: "General",
    },
    {
      Username: "berkanoz",
      MediaImpact: "31113",
      Followers: "7444",
      Category: "General",
    },
    {
      Username: "ezgiidil",
      MediaImpact: "30974",
      Followers: "1311",
      Category: "General",
    },
    {
      Username: "HeartlessLovahh",
      MediaImpact: "30550",
      Followers: "100",
      Category: "General",
    },
    {
      Username: "frandia125",
      MediaImpact: "30543",
      Followers: "3597",
      Category: "General",
    },
    {
      Username: "sarmadiqbal7",
      MediaImpact: "30248",
      Followers: "2736",
      Category: "General",
    },
    {
      Username: "endofwork",
      MediaImpact: "29731",
      Followers: "352",
      Category: "General",
    },
    {
      Username: "akifsarier",
      MediaImpact: "29065",
      Followers: "580",
      Category: "General",
    },
    {
      Username: "goreme1990",
      MediaImpact: "28980",
      Followers: "3900",
      Category: "General",
    },
    {
      Username: "t_kaloudis",
      MediaImpact: "28913",
      Followers: "1152",
      Category: "General",
    },
    {
      Username: "aysharalam",
      MediaImpact: "28908",
      Followers: "14512",
      Category: "General",
    },
    {
      Username: "PinguinFridolin",
      MediaImpact: "28479",
      Followers: "227",
      Category: "General",
    },
    {
      Username: "jochaguy",
      MediaImpact: "27754",
      Followers: "634",
      Category: "General",
    },
    {
      Username: "parametricarch",
      MediaImpact: "27540",
      Followers: "19289",
      Category: "General",
    },
    {
      Username: "rowingfinn",
      MediaImpact: "27263",
      Followers: "15156",
      Category: "General",
    },
    {
      Username: "osmangulveren",
      MediaImpact: "26936",
      Followers: "2125",
      Category: "General",
    },
    {
      Username: "AbuAmaanah",
      MediaImpact: "26670",
      Followers: "1600",
      Category: "General",
    },
    {
      Username: "dizissp",
      MediaImpact: "26152",
      Followers: "502",
      Category: "General",
    },
    {
      Username: "Hebah_ElOmari",
      MediaImpact: "25895",
      Followers: "1801",
      Category: "General",
    },
    {
      Username: "kartalbusemerke",
      MediaImpact: "25800",
      Followers: "11129",
      Category: "General",
    },
    {
      Username: "yerlibiryabanci",
      MediaImpact: "25781",
      Followers: "323",
      Category: "General",
    },
    {
      Username: "TheErimtanAngle",
      MediaImpact: "25169",
      Followers: "1864",
      Category: "General",
    },
    {
      Username: "CherieFireball",
      MediaImpact: "25141",
      Followers: "376",
      Category: "General",
    },
    {
      Username: "holistikbirey",
      MediaImpact: "25014",
      Followers: "2785",
      Category: "General",
    },
    {
      Username: "bdmr91",
      MediaImpact: "24759",
      Followers: "394",
      Category: "General",
    },
    {
      Username: "sitieajmal",
      MediaImpact: "24407",
      Followers: "123",
      Category: "General",
    },
    {
      Username: "metafluencer",
      MediaImpact: "23764",
      Followers: "1777",
      Category: "General",
    },
    {
      Username: "Ravale_Mohydin",
      MediaImpact: "23562",
      Followers: "5836",
      Category: "General",
    },
    {
      Username: "enginutkan",
      MediaImpact: "23360",
      Followers: "6297",
      Category: "General",
    },
    {
      Username: "Zulaila82153837",
      MediaImpact: "23347",
      Followers: "432",
      Category: "General",
    },
    {
      Username: "HalilBilsel",
      MediaImpact: "23264",
      Followers: "592",
      Category: "General",
    },
    {
      Username: "clm676896",
      MediaImpact: "23117",
      Followers: "1435",
      Category: "General",
    },
    {
      Username: "msafaksari",
      MediaImpact: "22932",
      Followers: "7455",
      Category: "General",
    },
    {
      Username: "demirelcemal45",
      MediaImpact: "22821",
      Followers: "1270",
      Category: "General",
    },
    {
      Username: "kong_lunastar",
      MediaImpact: "22582",
      Followers: "1118",
      Category: "General",
    },
    {
      Username: "DrewSparkR6",
      MediaImpact: "22507",
      Followers: "3704",
      Category: "General",
    },
    {
      Username: "lisafryar",
      MediaImpact: "22094",
      Followers: "1278",
      Category: "General",
    },
    {
      Username: "abragallabra",
      MediaImpact: "22030",
      Followers: "1015",
      Category: "General",
    },
    {
      Username: "IstanbulBlockWk",
      MediaImpact: "21657",
      Followers: "4258",
      Category: "General",
    },
    {
      Username: "StylesLimited",
      MediaImpact: "21579",
      Followers: "1202",
      Category: "General",
    },
    {
      Username: "ozlemyalim",
      MediaImpact: "21465",
      Followers: "2489",
      Category: "General",
    },
    {
      Username: "nico_lrx",
      MediaImpact: "21176",
      Followers: "2532",
      Category: "General",
    },
    {
      Username: "silasahinoz",
      MediaImpact: "20757",
      Followers: "379",
      Category: "General",
    },
    {
      Username: "steve_squires",
      MediaImpact: "20561",
      Followers: "574",
      Category: "General",
    },
    {
      Username: "sinefo",
      MediaImpact: "20165",
      Followers: "1947",
      Category: "General",
    },
  ],

  Government: [
    {
      Username: "riyazulkhaliq",
      MediaImpact: "1837503",
      Followers: "2719",
      Category: "Government",
    },
    {
      Username: "cover_up8d",
      MediaImpact: "393994",
      Followers: "758",
      Category: "Government",
    },
    {
      Username: "loosemoose97",
      MediaImpact: "392099",
      Followers: "918",
      Category: "Government",
    },
    {
      Username: "MariaRamosUK",
      MediaImpact: "310774",
      Followers: "16066",
      Category: "Government",
    },
    {
      Username: "LorenaLavinia",
      MediaImpact: "251760",
      Followers: "170",
      Category: "Government",
    },
    {
      Username: "mozsimsek",
      MediaImpact: "195373",
      Followers: "7772",
      Category: "Government",
    },
    {
      Username: "_duybeniekkan",
      MediaImpact: "168644",
      Followers: "138",
      Category: "Government",
    },
    {
      Username: "metesohtaoglu",
      MediaImpact: "134870",
      Followers: "69534",
      Category: "Government",
    },
    {
      Username: "businessturkey",
      MediaImpact: "131619",
      Followers: "1054",
      Category: "Government",
    },
    {
      Username: "AYCEMSUPREMACY",
      MediaImpact: "126814",
      Followers: "2040",
      Category: "Government",
    },
    {
      Username: "AConfusedLamb",
      MediaImpact: "126764",
      Followers: "4475",
      Category: "Government",
    },
    {
      Username: "MoonAlev",
      MediaImpact: "125782",
      Followers: "1753",
      Category: "Government",
    },
    {
      Username: "MELEK7452",
      MediaImpact: "110241",
      Followers: "4898",
      Category: "Government",
    },
    {
      Username: "Mardounyeh",
      MediaImpact: "107730",
      Followers: "112",
      Category: "Government",
    },
    {
      Username: "melisa_reyhan",
      MediaImpact: "103740",
      Followers: "4380",
      Category: "Government",
    },
    {
      Username: "OneNationTravel",
      MediaImpact: "88052",
      Followers: "14569",
      Category: "Government",
    },
    {
      Username: "ahb651",
      MediaImpact: "78277",
      Followers: "3377",
      Category: "Government",
    },
    {
      Username: "AbdulBillowAli",
      MediaImpact: "75948",
      Followers: "60650",
      Category: "Government",
    },
    {
      Username: "sagistgrup",
      MediaImpact: "75292",
      Followers: "2445",
      Category: "Government",
    },
    {
      Username: "lauxdby",
      MediaImpact: "70547",
      Followers: "1192",
      Category: "Government",
    },
    {
      Username: "arjenuijterlind",
      MediaImpact: "69999",
      Followers: "5533",
      Category: "Government",
    },
    {
      Username: "Mounzawi",
      MediaImpact: "66138",
      Followers: "217",
      Category: "Government",
    },
    {
      Username: "tugcebabaeren",
      MediaImpact: "55098",
      Followers: "1605",
      Category: "Government",
    },
    {
      Username: "erturkvarol",
      MediaImpact: "38702",
      Followers: "394",
      Category: "Government",
    },
    {
      Username: "HSYNYLMZ",
      MediaImpact: "38449",
      Followers: "2890",
      Category: "Government",
    },
    {
      Username: "enginguneysu",
      MediaImpact: "38204",
      Followers: "3120",
      Category: "Government",
    },
    {
      Username: "anews",
      MediaImpact: "35625",
      Followers: "35334",
      Category: "Government",
    },
    {
      Username: "mustafacopur",
      MediaImpact: "31310",
      Followers: "1495",
      Category: "Government",
    },
    {
      Username: "HeartlessLovahh",
      MediaImpact: "30550",
      Followers: "100",
      Category: "Government",
    },
    {
      Username: "imartinstrecker",
      MediaImpact: "28901",
      Followers: "769",
      Category: "Government",
    },
    {
      Username: "dizissp",
      MediaImpact: "26152",
      Followers: "502",
      Category: "Government",
    },
    {
      Username: "alihuseyinoglu",
      MediaImpact: "24571",
      Followers: "2870",
      Category: "Government",
    },
    {
      Username: "HalilBilsel",
      MediaImpact: "23264",
      Followers: "592",
      Category: "Government",
    },
    {
      Username: "sonnurbabayigit",
      MediaImpact: "20008",
      Followers: "271",
      Category: "Government",
    },
    {
      Username: "erhanicener",
      MediaImpact: "19878",
      Followers: "1452",
      Category: "Government",
    },
    {
      Username: "FulyaOzerkan",
      MediaImpact: "19518",
      Followers: "5237",
      Category: "Government",
    },
    {
      Username: "faribanawa",
      MediaImpact: "18707",
      Followers: "6119",
      Category: "Government",
    },
    {
      Username: "soyuerf",
      MediaImpact: "18664",
      Followers: "1275",
      Category: "Government",
    },
    {
      Username: "OguzTAkpinar",
      MediaImpact: "17875",
      Followers: "1327",
      Category: "Government",
    },
    {
      Username: "CGI_Istanbul",
      MediaImpact: "15823",
      Followers: "11276",
      Category: "Government",
    },
    {
      Username: "trtworldforum",
      MediaImpact: "15653",
      Followers: "14042",
      Category: "Government",
    },
  ],

  Economics: [
    {
      Username: "anews",
      MediaImpact: "355970",
      Followers: "35321",
      Category: "Economics",
    },
    {
      Username: "cover_up8d",
      MediaImpact: "263595",
      Followers: "756",
      Category: "Economics",
    },
    {
      Username: "AyseKulabas",
      MediaImpact: "105040",
      Followers: "1439",
      Category: "Economics",
    },
    {
      Username: "businessturkey",
      MediaImpact: "78850",
      Followers: "1055",
      Category: "Economics",
    },
    {
      Username: "OzgulErkisGozum",
      MediaImpact: "60690",
      Followers: "240",
      Category: "Economics",
    },
    {
      Username: "zdurranii",
      MediaImpact: "39640",
      Followers: "1384",
      Category: "Economics",
    },
    {
      Username: "bazaartimes",
      MediaImpact: "12200",
      Followers: "1089",
      Category: "Economics",
    },
    {
      Username: "TRTMoneyTalks",
      MediaImpact: "3280",
      Followers: "324",
      Category: "Economics",
    },
    {
      Username: "YenipinarZeynep",
      MediaImpact: "2290",
      Followers: "270",
      Category: "Economics",
    },
  ],

  Lifestyle: [
    {
      Username: "OneNationTravel",
      MediaImpact: "68816",
      Followers: "14570",
      Category: "Lifestyle",
    },
    {
      Username: "minemanapturel",
      MediaImpact: "58094",
      Followers: "3105",
      Category: "Lifestyle",
    },
    {
      Username: "KemalogluOz",
      MediaImpact: "41834",
      Followers: "8551",
      Category: "Lifestyle",
    },
    {
      Username: "TheiaSilver",
      MediaImpact: "22790",
      Followers: "809",
      Category: "Lifestyle",
    },
    {
      Username: "gozdekoc_82",
      MediaImpact: "22050",
      Followers: "210",
      Category: "Lifestyle",
    },
    {
      Username: "businessturkey",
      MediaImpact: "19667",
      Followers: "1055",
      Category: "Lifestyle",
    },
    {
      Username: "Ugokiintl1",
      MediaImpact: "15840",
      Followers: "154",
      Category: "Lifestyle",
    },
    {
      Username: "ishootbw",
      MediaImpact: "9320",
      Followers: "116",
      Category: "Lifestyle",
    },
    {
      Username: "SabbaghNasim",
      MediaImpact: "7950",
      Followers: "333",
      Category: "Lifestyle",
    },
    {
      Username: "mcenzura",
      MediaImpact: "5736",
      Followers: "381",
      Category: "Lifestyle",
    },
    {
      Username: "DmcMotiva",
      MediaImpact: "2990",
      Followers: "170",
      Category: "Lifestyle",
    },
    {
      Username: "O2Care_tur",
      MediaImpact: "1720",
      Followers: "170",
      Category: "Lifestyle",
    },
    {
      Username: "ApparelButtons",
      MediaImpact: "1470",
      Followers: "190",
      Category: "Lifestyle",
    },
    {
      Username: "TextileChic",
      MediaImpact: "1440",
      Followers: "580",
      Category: "Lifestyle",
    },
    {
      Username: "BarsamStore",
      MediaImpact: "1030",
      Followers: "60",
      Category: "Lifestyle",
    },
    {
      Username: "Vonartcreative",
      MediaImpact: "170",
      Followers: "110",
      Category: "Lifestyle",
    },
    {
      Username: "BraceletPappu",
      MediaImpact: "60",
      Followers: "30",
      Category: "Lifestyle",
    },
  ],

  Health: [
    {
      Username: "hairBurak",
      MediaImpact: "3567532",
      Followers: "5119",
      Category: "Health",
    },
    {
      Username: "atahanselekoglu",
      MediaImpact: "224187",
      Followers: "404",
      Category: "Health",
    },
    {
      Username: "Safa_Zakholy",
      MediaImpact: "196989",
      Followers: "4647",
      Category: "Health",
    },
    {
      Username: "BerrakBiz",
      MediaImpact: "120883",
      Followers: "6934",
      Category: "Health",
    },
    {
      Username: "Map_Addict",
      MediaImpact: "119344",
      Followers: "2179",
      Category: "Health",
    },
    {
      Username: "MejaFoss",
      MediaImpact: "116282",
      Followers: "11493",
      Category: "Health",
    },
    {
      Username: "sequencerider",
      MediaImpact: "72842",
      Followers: "476",
      Category: "Health",
    },
    {
      Username: "barryDstocker",
      MediaImpact: "71842",
      Followers: "1191",
      Category: "Health",
    },
    {
      Username: "vijivenkatesh",
      MediaImpact: "70252",
      Followers: "9559",
      Category: "Health",
    },
    {
      Username: "MoonAlev",
      MediaImpact: "66293",
      Followers: "1784",
      Category: "Health",
    },
    {
      Username: "kristin_violet1",
      MediaImpact: "65152",
      Followers: "118",
      Category: "Health",
    },
    {
      Username: "HappinessPatrol",
      MediaImpact: "56544",
      Followers: "1476",
      Category: "Health",
    },
    {
      Username: "shifthairtrans",
      MediaImpact: "44584",
      Followers: "831",
      Category: "Health",
    },
    {
      Username: "nevitdilmen",
      MediaImpact: "40740",
      Followers: "1322",
      Category: "Health",
    },
    {
      Username: "scorpioblr1968",
      MediaImpact: "37970",
      Followers: "440",
      Category: "Health",
    },
    {
      Username: "SSB1903",
      MediaImpact: "35285",
      Followers: "486",
      Category: "Health",
    },
    {
      Username: "EceYenice_",
      MediaImpact: "33218",
      Followers: "126",
      Category: "Health",
    },
    {
      Username: "osmangulveren",
      MediaImpact: "26936",
      Followers: "2125",
      Category: "Health",
    },
    {
      Username: "AConfusedLamb",
      MediaImpact: "26391",
      Followers: "4505",
      Category: "Health",
    },
    {
      Username: "KemalogluOz",
      MediaImpact: "25967",
      Followers: "8556",
      Category: "Health",
    },
    {
      Username: "Ravale_Mohydin",
      MediaImpact: "23562",
      Followers: "5836",
      Category: "Health",
    },
    {
      Username: "Zulaila82153837",
      MediaImpact: "23347",
      Followers: "432",
      Category: "Health",
    },
    {
      Username: "clm676896",
      MediaImpact: "23117",
      Followers: "1435",
      Category: "Health",
    },
    {
      Username: "DrewSparkR6",
      MediaImpact: "22507",
      Followers: "3704",
      Category: "Health",
    },
    {
      Username: "eceeksioglu",
      MediaImpact: "19701",
      Followers: "1531",
      Category: "Health",
    },
    {
      Username: "avenue_nh",
      MediaImpact: "19622",
      Followers: "4359",
      Category: "Health",
    },
  ],

  Culture: [
    {
      Username: "ahb651",
      MediaImpact: "148265",
      Followers: "3377",
      Category: "Culture",
    },
    {
      Username: "sagistgrup",
      MediaImpact: "148029",
      Followers: "2445",
      Category: "Culture",
    },
    {
      Username: "bassil_taleb",
      MediaImpact: "93965",
      Followers: "1473",
      Category: "Culture",
    },
    {
      Username: "arjenuijterlind",
      MediaImpact: "38144",
      Followers: "5533",
      Category: "Culture",
    },
    {
      Username: "anews",
      MediaImpact: "35599",
      Followers: "35321",
      Category: "Culture",
    },
    {
      Username: "parametricarch",
      MediaImpact: "27540",
      Followers: "19289",
      Category: "Culture",
    },
    {
      Username: "canergulten",
      MediaImpact: "18495",
      Followers: "955",
      Category: "Culture",
    },
    {
      Username: "nirmak",
      MediaImpact: "14980",
      Followers: "582",
      Category: "Culture",
    },
    {
      Username: "imartinstrecker",
      MediaImpact: "10546",
      Followers: "769",
      Category: "Culture",
    },
    {
      Username: "CVDTCLB",
      MediaImpact: "8598",
      Followers: "315",
      Category: "Culture",
    },
    {
      Username: "moon4art",
      MediaImpact: "7263",
      Followers: "1024",
      Category: "Culture",
    },
    {
      Username: "AlaSkateboards",
      MediaImpact: "7192",
      Followers: "460",
      Category: "Culture",
    },
    {
      Username: "Burak__Colak",
      MediaImpact: "6779",
      Followers: "508",
      Category: "Culture",
    },
    {
      Username: "retouchlab",
      MediaImpact: "6564",
      Followers: "3662",
      Category: "Culture",
    },
    {
      Username: "Enginyavuz",
      MediaImpact: "5757",
      Followers: "344",
      Category: "Culture",
    },
    {
      Username: "melo_mire",
      MediaImpact: "3899",
      Followers: "298",
      Category: "Culture",
    },
    {
      Username: "metadistilland",
      MediaImpact: "3267",
      Followers: "525",
      Category: "Culture",
    },
    {
      Username: "venmious7",
      MediaImpact: "887",
      Followers: "140",
      Category: "Culture",
    },
    {
      Username: "bazaarmixx",
      MediaImpact: "495",
      Followers: "473",
      Category: "Culture",
    },
    {
      Username: "garantiwebt",
      MediaImpact: "435",
      Followers: "360",
      Category: "Culture",
    },
    {
      Username: "AllaMariaBella",
      MediaImpact: "386",
      Followers: "660",
      Category: "Culture",
    },
    {
      Username: "mjmorradi",
      MediaImpact: "325",
      Followers: "430",
      Category: "Culture",
    },
    {
      Username: "mermerArt",
      MediaImpact: "232",
      Followers: "200",
      Category: "Culture",
    },
    {
      Username: "TextileChic",
      MediaImpact: "146",
      Followers: "580",
      Category: "Culture",
    },
    {
      Username: "CaveArtNFT",
      MediaImpact: "138",
      Followers: "80",
      Category: "Culture",
    },
  ],

  Education: [
    {
      Username: "cover_up8d",
      MediaImpact: "394071",
      Followers: "755",
      Category: "Education",
    },
    {
      Username: "trtworldforum",
      MediaImpact: "143740",
      Followers: "14046",
      Category: "Education",
    },
    {
      Username: "OzgulErkisGozum",
      MediaImpact: "60700",
      Followers: "240",
      Category: "Education",
    },
    {
      Username: "IRCICA",
      MediaImpact: "50640",
      Followers: "4932",
      Category: "Education",
    },
    {
      Username: "guvencat",
      MediaImpact: "49480",
      Followers: "2815",
      Category: "Education",
    },
    {
      Username: "AYDINALPMustafa",
      MediaImpact: "16090",
      Followers: "1670",
      Category: "Education",
    },
    {
      Username: "univechain",
      MediaImpact: "4010",
      Followers: "1420",
      Category: "Education",
    },
    {
      Username: "Mavili_Global",
      MediaImpact: "1030",
      Followers: "760",
      Category: "Education",
    },
    {
      Username: "wannabetallert1",
      MediaImpact: "930",
      Followers: "440",
      Category: "Education",
    },
    {
      Username: "perculus",
      MediaImpact: "680",
      Followers: "420",
      Category: "Education",
    },
    {
      Username: "Mirayfiliz___",
      MediaImpact: "530",
      Followers: "30",
      Category: "Education",
    },
    {
      Username: "millercarterba",
      MediaImpact: "100",
      Followers: "20",
      Category: "Education",
    },
  ],

  Traffic: [
    {
      Username: "HDNER",
      MediaImpact: "276613",
      Followers: "276536",
      Category: "Traffic",
    },
    {
      Username: "KeremGarip5",
      MediaImpact: "186423",
      Followers: "2642",
      Category: "Traffic",
    },
    {
      Username: "TRTWorldNow",
      MediaImpact: "183274",
      Followers: "183253",
      Category: "Traffic",
    },
    {
      Username: "RobinAdamsZA",
      MediaImpact: "145934",
      Followers: "15812",
      Category: "Traffic",
    },
    {
      Username: "NabellaAnuar",
      MediaImpact: "102968",
      Followers: "96924",
      Category: "Traffic",
    },
    {
      Username: "maryyasmine",
      MediaImpact: "90922",
      Followers: "6227",
      Category: "Traffic",
    },
    {
      Username: "Ernesthernand15",
      MediaImpact: "84633",
      Followers: "3063",
      Category: "Traffic",
    },
    {
      Username: "ferhatcekin",
      MediaImpact: "81987",
      Followers: "943",
      Category: "Traffic",
    },
    {
      Username: "opheligarcia",
      MediaImpact: "64744",
      Followers: "1710",
      Category: "Traffic",
    },
    {
      Username: "cjaythecreator",
      MediaImpact: "49574",
      Followers: "2482",
      Category: "Traffic",
    },
    {
      Username: "MightyFineCopy_",
      MediaImpact: "43693",
      Followers: "4351",
      Category: "Traffic",
    },
    {
      Username: "PrisyncCom",
      MediaImpact: "39895",
      Followers: "2390",
      Category: "Traffic",
    },
    {
      Username: "arjenuijterlind",
      MediaImpact: "38397",
      Followers: "5592",
      Category: "Traffic",
    },
    {
      Username: "anews",
      MediaImpact: "35530",
      Followers: "35253",
      Category: "Traffic",
    },
    {
      Username: "Fernando1Angulo",
      MediaImpact: "34490",
      Followers: "12932",
      Category: "Traffic",
    },
    {
      Username: "KorayGubur",
      MediaImpact: "31722",
      Followers: "13870",
      Category: "Traffic",
    },
    {
      Username: "yerlibiryabanci",
      MediaImpact: "25781",
      Followers: "323",
      Category: "Traffic",
    },
    {
      Username: "sequencerider",
      MediaImpact: "25526",
      Followers: "476",
      Category: "Traffic",
    },
    {
      Username: "nico_lrx",
      MediaImpact: "21176",
      Followers: "2532",
      Category: "Traffic",
    },
    {
      Username: "Saida_Zahidova",
      MediaImpact: "18486",
      Followers: "5510",
      Category: "Traffic",
    },
    {
      Username: "maduako10",
      MediaImpact: "15692",
      Followers: "909",
      Category: "Traffic",
    },
    {
      Username: "juliahahntv",
      MediaImpact: "11570",
      Followers: "7149",
      Category: "Traffic",
    },
    {
      Username: "nyathikano",
      MediaImpact: "10740",
      Followers: "6115",
      Category: "Traffic",
    },
    {
      Username: "oyasan",
      MediaImpact: "9572",
      Followers: "2237",
      Category: "Traffic",
    },
    {
      Username: "businessturkey",
      MediaImpact: "8095",
      Followers: "1053",
      Category: "Traffic",
    },
    {
      Username: "pat_syk",
      MediaImpact: "5969",
      Followers: "2142",
      Category: "Traffic",
    },
  ],
};
