export const data = [
  {
    Username: "riyazulkhaliq",
    MediaImpact: "5137528",
    Followers: "2768",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "cover_up8d",
    MediaImpact: "5113897",
    Followers: "787",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "hairBurak",
    MediaImpact: "3567532",
    Followers: "5119",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "MariaRamosUK",
    MediaImpact: "1132977",
    Followers: "16599",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "fatihaydin_TC",
    MediaImpact: "594878",
    Followers: "12048",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "RenaNetjes",
    MediaImpact: "431805",
    Followers: "26427",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "businessturkey",
    MediaImpact: "393298",
    Followers: "1055",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "loosemoose97",
    MediaImpact: "392099",
    Followers: "918",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "mozsimsek",
    MediaImpact: "377000",
    Followers: "7772",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "sagistgrup",
    MediaImpact: "368852",
    Followers: "2560",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "mikelayestaran",
    MediaImpact: "336125",
    Followers: "180860",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "arjenuijterlind",
    MediaImpact: "294076",
    Followers: "5595",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "OneNationTravel",
    MediaImpact: "284718",
    Followers: "14570",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "HDNER",
    MediaImpact: "276613",
    Followers: "276536",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "metesohtaoglu",
    MediaImpact: "274430",
    Followers: "69699",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "MoonAlev",
    MediaImpact: "253373",
    Followers: "1784",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "LorenaLavinia",
    MediaImpact: "251760",
    Followers: "170",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "CaKizil",
    MediaImpact: "233651",
    Followers: "208422",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "atahanselekoglu",
    MediaImpact: "224187",
    Followers: "404",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "ahb651",
    MediaImpact: "218214",
    Followers: "3377",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "minemanapturel",
    MediaImpact: "218169",
    Followers: "3105",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "MELEK7452",
    MediaImpact: "211504",
    Followers: "4898",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Safa_Zakholy",
    MediaImpact: "196989",
    Followers: "4647",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "kristin_violet1",
    MediaImpact: "192507",
    Followers: "118",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "KeremGarip5",
    MediaImpact: "186423",
    Followers: "2642",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "ze7nep",
    MediaImpact: "185889",
    Followers: "847",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "TRTWorldNow",
    MediaImpact: "183274",
    Followers: "183253",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "VialliChelseaFC",
    MediaImpact: "174756",
    Followers: "16680",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "sukru66guven",
    MediaImpact: "170353",
    Followers: "5541",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "_duybeniekkan",
    MediaImpact: "168644",
    Followers: "138",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "AConfusedLamb",
    MediaImpact: "155816",
    Followers: "4505",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "RobinAdamsZA",
    MediaImpact: "145934",
    Followers: "15812",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Saida_Zahidova",
    MediaImpact: "138774",
    Followers: "5510",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "anilaali",
    MediaImpact: "138700",
    Followers: "21814",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "imamoglu_int",
    MediaImpact: "134078",
    Followers: "132157",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "ikaveri",
    MediaImpact: "129807",
    Followers: "67875",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Mounzawi",
    MediaImpact: "129217",
    Followers: "217",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "AYCEMSUPREMACY",
    MediaImpact: "126814",
    Followers: "2040",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Djyeo_coffee",
    MediaImpact: "124875",
    Followers: "4711",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "zaferkarabalik",
    MediaImpact: "122139",
    Followers: "33456",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "EKrkoglu",
    MediaImpact: "122041",
    Followers: "185",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "BerrakBiz",
    MediaImpact: "120883",
    Followers: "6934",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Map_Addict",
    MediaImpact: "119344",
    Followers: "2179",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "DarleyNewman",
    MediaImpact: "119210",
    Followers: "20728",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "MejaFoss",
    MediaImpact: "116282",
    Followers: "11493",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "hansvantelling",
    MediaImpact: "112816",
    Followers: "68062",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "tugcebabaeren",
    MediaImpact: "108564",
    Followers: "1605",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Mardounyeh",
    MediaImpact: "107730",
    Followers: "112",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "izharnephrol",
    MediaImpact: "107247",
    Followers: "1015",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "HappinessPatrol",
    MediaImpact: "106650",
    Followers: "1476",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "melisa_reyhan",
    MediaImpact: "103740",
    Followers: "4380",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "AbangOmar",
    MediaImpact: "103428",
    Followers: "2963",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "NabellaAnuar",
    MediaImpact: "102968",
    Followers: "96924",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "AbdulBillowAli",
    MediaImpact: "97881",
    Followers: "60665",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "sequencerider",
    MediaImpact: "96509",
    Followers: "476",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "bassil_taleb",
    MediaImpact: "93965",
    Followers: "1473",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "maryyasmine",
    MediaImpact: "90922",
    Followers: "6227",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Jzcheniah",
    MediaImpact: "86646",
    Followers: "150",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "UncleLoo",
    MediaImpact: "86566",
    Followers: "1174",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "krista_slade",
    MediaImpact: "85250",
    Followers: "1083",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Ernesthernand15",
    MediaImpact: "84633",
    Followers: "3063",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "ferhatcekin",
    MediaImpact: "81987",
    Followers: "943",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "SezinOney",
    MediaImpact: "78610",
    Followers: "52420",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "imartinstrecker",
    MediaImpact: "76080",
    Followers: "771",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "erturkvarol",
    MediaImpact: "75713",
    Followers: "394",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "TheTokyoDerek",
    MediaImpact: "74772",
    Followers: "797",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "MeaganWristen",
    MediaImpact: "73043",
    Followers: "46126",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "barryDstocker",
    MediaImpact: "71842",
    Followers: "1191",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "EsraKarahindiba",
    MediaImpact: "71753",
    Followers: "24547",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "enginguneysu",
    MediaImpact: "71170",
    Followers: "3120",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "lauxdby",
    MediaImpact: "70547",
    Followers: "1192",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "iamhuraira",
    MediaImpact: "70367",
    Followers: "44",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "vijivenkatesh",
    MediaImpact: "70252",
    Followers: "9559",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "LunaSafwan",
    MediaImpact: "65054",
    Followers: "29497",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "opheligarcia",
    MediaImpact: "64744",
    Followers: "1710",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "kardelenyarli",
    MediaImpact: "60178",
    Followers: "17627",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Sirisakc",
    MediaImpact: "59954",
    Followers: "979",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "sonnurbabayigit",
    MediaImpact: "58540",
    Followers: "279",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "mustafacopur",
    MediaImpact: "58284",
    Followers: "1604",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Iam_Grateful_xo",
    MediaImpact: "58028",
    Followers: "3452",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "KemalogluOz",
    MediaImpact: "57551",
    Followers: "8556",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "KidCon",
    MediaImpact: "55516",
    Followers: "759",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "maryanntheresa",
    MediaImpact: "55254",
    Followers: "1776",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "shifthairtrans",
    MediaImpact: "54311",
    Followers: "836",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "DGPhotography9",
    MediaImpact: "53968",
    Followers: "1896",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Daniel_Miller8",
    MediaImpact: "52333",
    Followers: "7441",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "itsawais85",
    MediaImpact: "50757",
    Followers: "503",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "jlo_said",
    MediaImpact: "49811",
    Followers: "6813",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "astro_ash_",
    MediaImpact: "49613",
    Followers: "801",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "cjaythecreator",
    MediaImpact: "49574",
    Followers: "2482",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "CommsCraig",
    MediaImpact: "45529",
    Followers: "20341",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "aliboomaye",
    MediaImpact: "45240",
    Followers: "7753",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "alihuseyinoglu",
    MediaImpact: "43981",
    Followers: "2872",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "MightyFineCopy_",
    MediaImpact: "43693",
    Followers: "4351",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "fevzibulganHZK",
    MediaImpact: "42790",
    Followers: "24680",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "FezaRemziMD",
    MediaImpact: "41334",
    Followers: "5556",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "AyhanKaya14",
    MediaImpact: "41073",
    Followers: "5786",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "nevitdilmen",
    MediaImpact: "40740",
    Followers: "1322",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "jiggaholic1",
    MediaImpact: "40582",
    Followers: "2195",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "PrisyncCom",
    MediaImpact: "39895",
    Followers: "2390",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "alifnomad",
    MediaImpact: "39736",
    Followers: "703",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "HSYNYLMZ",
    MediaImpact: "38449",
    Followers: "2890",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "scorpioblr1968",
    MediaImpact: "37970",
    Followers: "440",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "estern53",
    MediaImpact: "36830",
    Followers: "131",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "gabeysena",
    MediaImpact: "36414",
    Followers: "458",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Kaan01234",
    MediaImpact: "36400",
    Followers: "232",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "anews",
    MediaImpact: "35694",
    Followers: "35334",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "SSB1903",
    MediaImpact: "35285",
    Followers: "486",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "soyuerf",
    MediaImpact: "34536",
    Followers: "1278",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Fernando1Angulo",
    MediaImpact: "34490",
    Followers: "12932",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "reemosama",
    MediaImpact: "33659",
    Followers: "1102",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "faribanawa",
    MediaImpact: "33635",
    Followers: "6119",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "ShoaibReema",
    MediaImpact: "33534",
    Followers: "665",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "farah912",
    MediaImpact: "33401",
    Followers: "288",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "EceYenice_",
    MediaImpact: "33218",
    Followers: "126",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "cijohnstone23",
    MediaImpact: "32817",
    Followers: "273",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "TedToToe",
    MediaImpact: "32765",
    Followers: "1016",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "KenanPoleo",
    MediaImpact: "32693",
    Followers: "25992",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "KirkhamTravel",
    MediaImpact: "32508",
    Followers: "694",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "KorayGubur",
    MediaImpact: "31722",
    Followers: "13870",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "FulyaOzerkan",
    MediaImpact: "31267",
    Followers: "5238",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "berkanoz",
    MediaImpact: "31113",
    Followers: "7444",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "ezgiidil",
    MediaImpact: "30974",
    Followers: "1311",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "HeartlessLovahh",
    MediaImpact: "30550",
    Followers: "100",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "frandia125",
    MediaImpact: "30543",
    Followers: "3597",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "sarmadiqbal7",
    MediaImpact: "30248",
    Followers: "2736",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "endofwork",
    MediaImpact: "29731",
    Followers: "352",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "akifsarier",
    MediaImpact: "29065",
    Followers: "580",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "goreme1990",
    MediaImpact: "28980",
    Followers: "3900",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "t_kaloudis",
    MediaImpact: "28913",
    Followers: "1152",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "aysharalam",
    MediaImpact: "28908",
    Followers: "14512",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "PinguinFridolin",
    MediaImpact: "28479",
    Followers: "227",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "jochaguy",
    MediaImpact: "27754",
    Followers: "634",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "parametricarch",
    MediaImpact: "27540",
    Followers: "19289",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "rowingfinn",
    MediaImpact: "27263",
    Followers: "15156",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "osmangulveren",
    MediaImpact: "26936",
    Followers: "2125",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "AbuAmaanah",
    MediaImpact: "26670",
    Followers: "1600",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "dizissp",
    MediaImpact: "26152",
    Followers: "502",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Hebah_ElOmari",
    MediaImpact: "25895",
    Followers: "1801",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "kartalbusemerke",
    MediaImpact: "25800",
    Followers: "11129",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "yerlibiryabanci",
    MediaImpact: "25781",
    Followers: "323",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "TheErimtanAngle",
    MediaImpact: "25169",
    Followers: "1864",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "CherieFireball",
    MediaImpact: "25141",
    Followers: "376",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "holistikbirey",
    MediaImpact: "25014",
    Followers: "2785",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "bdmr91",
    MediaImpact: "24759",
    Followers: "394",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "sitieajmal",
    MediaImpact: "24407",
    Followers: "123",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "metafluencer",
    MediaImpact: "23764",
    Followers: "1777",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Ravale_Mohydin",
    MediaImpact: "23562",
    Followers: "5836",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "enginutkan",
    MediaImpact: "23360",
    Followers: "6297",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Zulaila82153837",
    MediaImpact: "23347",
    Followers: "432",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "HalilBilsel",
    MediaImpact: "23264",
    Followers: "592",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "clm676896",
    MediaImpact: "23117",
    Followers: "1435",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "msafaksari",
    MediaImpact: "22932",
    Followers: "7455",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "demirelcemal45",
    MediaImpact: "22821",
    Followers: "1270",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "kong_lunastar",
    MediaImpact: "22582",
    Followers: "1118",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "DrewSparkR6",
    MediaImpact: "22507",
    Followers: "3704",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "lisafryar",
    MediaImpact: "22094",
    Followers: "1278",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "abragallabra",
    MediaImpact: "22030",
    Followers: "1015",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "IstanbulBlockWk",
    MediaImpact: "21657",
    Followers: "4258",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "StylesLimited",
    MediaImpact: "21579",
    Followers: "1202",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "ozlemyalim",
    MediaImpact: "21465",
    Followers: "2489",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "nico_lrx",
    MediaImpact: "21176",
    Followers: "2532",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "silasahinoz",
    MediaImpact: "20757",
    Followers: "379",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "steve_squires",
    MediaImpact: "20561",
    Followers: "574",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "sinefo",
    MediaImpact: "20165",
    Followers: "1947",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "riyazulkhaliq",
    MediaImpact: "1837503",
    Followers: "2719",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "cover_up8d",
    MediaImpact: "393994",
    Followers: "758",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "loosemoose97",
    MediaImpact: "392099",
    Followers: "918",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "MariaRamosUK",
    MediaImpact: "310774",
    Followers: "16066",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "LorenaLavinia",
    MediaImpact: "251760",
    Followers: "170",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "mozsimsek",
    MediaImpact: "195373",
    Followers: "7772",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "_duybeniekkan",
    MediaImpact: "168644",
    Followers: "138",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "metesohtaoglu",
    MediaImpact: "134870",
    Followers: "69534",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "businessturkey",
    MediaImpact: "131619",
    Followers: "1054",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "AYCEMSUPREMACY",
    MediaImpact: "126814",
    Followers: "2040",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "AConfusedLamb",
    MediaImpact: "126764",
    Followers: "4475",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "MoonAlev",
    MediaImpact: "125782",
    Followers: "1753",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "MELEK7452",
    MediaImpact: "110241",
    Followers: "4898",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "Mardounyeh",
    MediaImpact: "107730",
    Followers: "112",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "melisa_reyhan",
    MediaImpact: "103740",
    Followers: "4380",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "OneNationTravel",
    MediaImpact: "88052",
    Followers: "14569",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "ahb651",
    MediaImpact: "78277",
    Followers: "3377",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "AbdulBillowAli",
    MediaImpact: "75948",
    Followers: "60650",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "sagistgrup",
    MediaImpact: "75292",
    Followers: "2445",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "lauxdby",
    MediaImpact: "70547",
    Followers: "1192",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "arjenuijterlind",
    MediaImpact: "69999",
    Followers: "5533",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "Mounzawi",
    MediaImpact: "66138",
    Followers: "217",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "tugcebabaeren",
    MediaImpact: "55098",
    Followers: "1605",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "erturkvarol",
    MediaImpact: "38702",
    Followers: "394",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "HSYNYLMZ",
    MediaImpact: "38449",
    Followers: "2890",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "enginguneysu",
    MediaImpact: "38204",
    Followers: "3120",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "anews",
    MediaImpact: "35625",
    Followers: "35334",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "mustafacopur",
    MediaImpact: "31310",
    Followers: "1495",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "HeartlessLovahh",
    MediaImpact: "30550",
    Followers: "100",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "imartinstrecker",
    MediaImpact: "28901",
    Followers: "769",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "dizissp",
    MediaImpact: "26152",
    Followers: "502",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "alihuseyinoglu",
    MediaImpact: "24571",
    Followers: "2870",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "HalilBilsel",
    MediaImpact: "23264",
    Followers: "592",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "sonnurbabayigit",
    MediaImpact: "20008",
    Followers: "271",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "erhanicener",
    MediaImpact: "19878",
    Followers: "1452",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "FulyaOzerkan",
    MediaImpact: "19518",
    Followers: "5237",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "faribanawa",
    MediaImpact: "18707",
    Followers: "6119",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "soyuerf",
    MediaImpact: "18664",
    Followers: "1275",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "OguzTAkpinar",
    MediaImpact: "17875",
    Followers: "1327",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "CGI_Istanbul",
    MediaImpact: "15823",
    Followers: "11276",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "trtworldforum",
    MediaImpact: "15653",
    Followers: "14042",
    Category: "Government",
    CategoryAll: "All",
  },
  {
    Username: "anews",
    MediaImpact: "355970",
    Followers: "35321",
    Category: "Economics",
    CategoryAll: "All",
  },
  {
    Username: "cover_up8d",
    MediaImpact: "263595",
    Followers: "756",
    Category: "Economics",
    CategoryAll: "All",
  },
  {
    Username: "AyseKulabas",
    MediaImpact: "105040",
    Followers: "1439",
    Category: "Economics",
    CategoryAll: "All",
  },
  {
    Username: "businessturkey",
    MediaImpact: "78850",
    Followers: "1055",
    Category: "Economics",
    CategoryAll: "All",
  },
  {
    Username: "OzgulErkisGozum",
    MediaImpact: "60690",
    Followers: "240",
    Category: "Economics",
    CategoryAll: "All",
  },
  {
    Username: "zdurranii",
    MediaImpact: "39640",
    Followers: "1384",
    Category: "Economics",
    CategoryAll: "All",
  },
  {
    Username: "bazaartimes",
    MediaImpact: "12200",
    Followers: "1089",
    Category: "Economics",
    CategoryAll: "All",
  },
  {
    Username: "TRTMoneyTalks",
    MediaImpact: "3280",
    Followers: "324",
    Category: "Economics",
    CategoryAll: "All",
  },
  {
    Username: "YenipinarZeynep",
    MediaImpact: "2290",
    Followers: "270",
    Category: "Economics",
    CategoryAll: "All",
  },
  {
    Username: "cover_up8d",
    MediaImpact: "394071",
    Followers: "755",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "trtworldforum",
    MediaImpact: "143740",
    Followers: "14046",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "OzgulErkisGozum",
    MediaImpact: "60700",
    Followers: "240",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "IRCICA",
    MediaImpact: "50640",
    Followers: "4932",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "guvencat",
    MediaImpact: "49480",
    Followers: "2815",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "AYDINALPMustafa",
    MediaImpact: "16090",
    Followers: "1670",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "univechain",
    MediaImpact: "4010",
    Followers: "1420",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "Mavili_Global",
    MediaImpact: "1030",
    Followers: "760",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "wannabetallert1",
    MediaImpact: "930",
    Followers: "440",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "perculus",
    MediaImpact: "680",
    Followers: "420",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "Mirayfiliz___",
    MediaImpact: "530",
    Followers: "30",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "millercarterba",
    MediaImpact: "100",
    Followers: "20",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "ahb651",
    MediaImpact: "148265",
    Followers: "3377",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "sagistgrup",
    MediaImpact: "148029",
    Followers: "2445",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "bassil_taleb",
    MediaImpact: "93965",
    Followers: "1473",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "arjenuijterlind",
    MediaImpact: "38144",
    Followers: "5533",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "anews",
    MediaImpact: "35599",
    Followers: "35321",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "parametricarch",
    MediaImpact: "27540",
    Followers: "19289",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "canergulten",
    MediaImpact: "18495",
    Followers: "955",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "nirmak",
    MediaImpact: "14980",
    Followers: "582",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "imartinstrecker",
    MediaImpact: "10546",
    Followers: "769",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "CVDTCLB",
    MediaImpact: "8598",
    Followers: "315",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "moon4art",
    MediaImpact: "7263",
    Followers: "1024",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "AlaSkateboards",
    MediaImpact: "7192",
    Followers: "460",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "Burak__Colak",
    MediaImpact: "6779",
    Followers: "508",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "retouchlab",
    MediaImpact: "6564",
    Followers: "3662",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "Enginyavuz",
    MediaImpact: "5757",
    Followers: "344",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "melo_mire",
    MediaImpact: "3899",
    Followers: "298",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "metadistilland",
    MediaImpact: "3267",
    Followers: "525",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "venmious7",
    MediaImpact: "887",
    Followers: "140",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "bazaarmixx",
    MediaImpact: "495",
    Followers: "473",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "garantiwebt",
    MediaImpact: "435",
    Followers: "360",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "AllaMariaBella",
    MediaImpact: "386",
    Followers: "660",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "mjmorradi",
    MediaImpact: "325",
    Followers: "430",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "mermerArt",
    MediaImpact: "232",
    Followers: "200",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "TextileChic",
    MediaImpact: "146",
    Followers: "580",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "CaveArtNFT",
    MediaImpact: "138",
    Followers: "80",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "OneNationTravel",
    MediaImpact: "68816",
    Followers: "14570",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "minemanapturel",
    MediaImpact: "58094",
    Followers: "3105",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "KemalogluOz",
    MediaImpact: "41834",
    Followers: "8551",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "TheiaSilver",
    MediaImpact: "22790",
    Followers: "809",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "gozdekoc_82",
    MediaImpact: "22050",
    Followers: "210",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "businessturkey",
    MediaImpact: "19667",
    Followers: "1055",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "Ugokiintl1",
    MediaImpact: "15840",
    Followers: "154",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "ishootbw",
    MediaImpact: "9320",
    Followers: "116",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "SabbaghNasim",
    MediaImpact: "7950",
    Followers: "333",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "mcenzura",
    MediaImpact: "5736",
    Followers: "381",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "DmcMotiva",
    MediaImpact: "2990",
    Followers: "170",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "O2Care_tur",
    MediaImpact: "1720",
    Followers: "170",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "ApparelButtons",
    MediaImpact: "1470",
    Followers: "190",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "TextileChic",
    MediaImpact: "1440",
    Followers: "580",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "BarsamStore",
    MediaImpact: "1030",
    Followers: "60",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "Vonartcreative",
    MediaImpact: "170",
    Followers: "110",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "BraceletPappu",
    MediaImpact: "60",
    Followers: "30",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "hairBurak",
    MediaImpact: "3567532",
    Followers: "5119",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "atahanselekoglu",
    MediaImpact: "224187",
    Followers: "404",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "Safa_Zakholy",
    MediaImpact: "196989",
    Followers: "4647",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "BerrakBiz",
    MediaImpact: "120883",
    Followers: "6934",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "Map_Addict",
    MediaImpact: "119344",
    Followers: "2179",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "MejaFoss",
    MediaImpact: "116282",
    Followers: "11493",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "sequencerider",
    MediaImpact: "72842",
    Followers: "476",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "barryDstocker",
    MediaImpact: "71842",
    Followers: "1191",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "vijivenkatesh",
    MediaImpact: "70252",
    Followers: "9559",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "MoonAlev",
    MediaImpact: "66293",
    Followers: "1784",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "kristin_violet1",
    MediaImpact: "65152",
    Followers: "118",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "HappinessPatrol",
    MediaImpact: "56544",
    Followers: "1476",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "shifthairtrans",
    MediaImpact: "44584",
    Followers: "831",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "nevitdilmen",
    MediaImpact: "40740",
    Followers: "1322",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "scorpioblr1968",
    MediaImpact: "37970",
    Followers: "440",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "SSB1903",
    MediaImpact: "35285",
    Followers: "486",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "EceYenice_",
    MediaImpact: "33218",
    Followers: "126",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "osmangulveren",
    MediaImpact: "26936",
    Followers: "2125",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "AConfusedLamb",
    MediaImpact: "26391",
    Followers: "4505",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "KemalogluOz",
    MediaImpact: "25967",
    Followers: "8556",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "Ravale_Mohydin",
    MediaImpact: "23562",
    Followers: "5836",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "Zulaila82153837",
    MediaImpact: "23347",
    Followers: "432",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "clm676896",
    MediaImpact: "23117",
    Followers: "1435",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "DrewSparkR6",
    MediaImpact: "22507",
    Followers: "3704",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "eceeksioglu",
    MediaImpact: "19701",
    Followers: "1531",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "avenue_nh",
    MediaImpact: "19622",
    Followers: "4359",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "HDNER",
    MediaImpact: "276613",
    Followers: "276536",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "KeremGarip5",
    MediaImpact: "186423",
    Followers: "2642",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "TRTWorldNow",
    MediaImpact: "183274",
    Followers: "183253",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "RobinAdamsZA",
    MediaImpact: "145934",
    Followers: "15812",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "NabellaAnuar",
    MediaImpact: "102968",
    Followers: "96924",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "maryyasmine",
    MediaImpact: "90922",
    Followers: "6227",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "Ernesthernand15",
    MediaImpact: "84633",
    Followers: "3063",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "ferhatcekin",
    MediaImpact: "81987",
    Followers: "943",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "opheligarcia",
    MediaImpact: "64744",
    Followers: "1710",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "cjaythecreator",
    MediaImpact: "49574",
    Followers: "2482",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "MightyFineCopy_",
    MediaImpact: "43693",
    Followers: "4351",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "PrisyncCom",
    MediaImpact: "39895",
    Followers: "2390",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "arjenuijterlind",
    MediaImpact: "38397",
    Followers: "5592",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "anews",
    MediaImpact: "35530",
    Followers: "35253",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "Fernando1Angulo",
    MediaImpact: "34490",
    Followers: "12932",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "KorayGubur",
    MediaImpact: "31722",
    Followers: "13870",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "yerlibiryabanci",
    MediaImpact: "25781",
    Followers: "323",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "sequencerider",
    MediaImpact: "25526",
    Followers: "476",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "nico_lrx",
    MediaImpact: "21176",
    Followers: "2532",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "Saida_Zahidova",
    MediaImpact: "18486",
    Followers: "5510",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "maduako10",
    MediaImpact: "15692",
    Followers: "909",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "juliahahntv",
    MediaImpact: "11570",
    Followers: "7149",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "nyathikano",
    MediaImpact: "10740",
    Followers: "6115",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "oyasan",
    MediaImpact: "9572",
    Followers: "2237",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "businessturkey",
    MediaImpact: "8095",
    Followers: "1053",
    Category: "Traffic",
    CategoryAll: "All",
  },
  {
    Username: "pat_syk",
    MediaImpact: "5969",
    Followers: "2142",
    Category: "Traffic",
    CategoryAll: "All",
  },
];
