export const data = [
  {
    Username: "cover_up8d",
    MediaImpact: "1176851",
    Followers: "758",
    Engagement: "1174201",
    Category: "Education",
    CategoryAll: "All",
  },
  {
    Username: "riyazulkhaliq",
    MediaImpact: "464714",
    Followers: "2707",
    Engagement: "457009",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "loosemoose97",
    MediaImpact: "392103",
    Followers: "918",
    Engagement: "390819",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "LorenaLavinia",
    MediaImpact: "251766",
    Followers: "170",
    Engagement: "251526",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "sagistgrup",
    MediaImpact: "220765",
    Followers: "2445",
    Engagement: "218206",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "ahb651",
    MediaImpact: "218217",
    Followers: "3377",
    Engagement: "209885",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "_duybeniekkan",
    MediaImpact: "168709",
    Followers: "138",
    Engagement: "168462",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "businessturkey",
    MediaImpact: "155216",
    Followers: "1055",
    Engagement: "153225",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "metesohtaoglu",
    MediaImpact: "134875",
    Followers: "69534",
    Engagement: "62007",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "AYCEMSUPREMACY",
    MediaImpact: "126820",
    Followers: "2040",
    Engagement: "124503",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "AConfusedLamb",
    MediaImpact: "126782",
    Followers: "4475",
    Engagement: "122189",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "OneNationTravel",
    MediaImpact: "126538",
    Followers: "14570",
    Engagement: "96199",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "MoonAlev",
    MediaImpact: "125784",
    Followers: "1753",
    Engagement: "123304",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Mardounyeh",
    MediaImpact: "107736",
    Followers: "112",
    Engagement: "107306",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "bassil_taleb",
    MediaImpact: "93969",
    Followers: "1473",
    Engagement: "91181",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "MariaRamosUK",
    MediaImpact: "85353",
    Followers: "16059",
    Engagement: "64335",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "AbdulBillowAli",
    MediaImpact: "75950",
    Followers: "60650",
    Engagement: "14599",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "lauxdby",
    MediaImpact: "70555",
    Followers: "1192",
    Engagement: "69337",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "Mounzawi",
    MediaImpact: "66139",
    Followers: "217",
    Engagement: "62879",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "minemanapturel",
    MediaImpact: "58095",
    Followers: "3105",
    Engagement: "52802",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "tugcebabaeren",
    MediaImpact: "55099",
    Followers: "1605",
    Engagement: "53156",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "KemalogluOz",
    MediaImpact: "41836",
    Followers: "8551",
    Engagement: "31586",
    Category: "Lifestyle",
    CategoryAll: "All",
  },
  {
    Username: "nevitdilmen",
    MediaImpact: "40741",
    Followers: "1322",
    Engagement: "37268",
    Category: "Health",
    CategoryAll: "All",
  },
  {
    Username: "HSYNYLMZ",
    MediaImpact: "38451",
    Followers: "2890",
    Engagement: "33560",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "enginguneysu",
    MediaImpact: "38205",
    Followers: "3120",
    Engagement: "32618",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "anews",
    MediaImpact: "35645",
    Followers: "35334",
    Engagement: "37",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "mustafacopur",
    MediaImpact: "31311",
    Followers: "1495",
    Engagement: "26222",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "HeartlessLovahh",
    MediaImpact: "30559",
    Followers: "100",
    Engagement: "30329",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "parametricarch",
    MediaImpact: "27541",
    Followers: "19289",
    Engagement: "8181",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "dizissp",
    MediaImpact: "26155",
    Followers: "502",
    Engagement: "25187",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "HalilBilsel",
    MediaImpact: "23265",
    Followers: "592",
    Engagement: "22015",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "sonnurbabayigit",
    MediaImpact: "20009",
    Followers: "271",
    Engagement: "18906",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "erhanicener",
    MediaImpact: "19880",
    Followers: "1452",
    Engagement: "16556",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "FulyaOzerkan",
    MediaImpact: "19527",
    Followers: "5237",
    Engagement: "12992",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "faribanawa",
    MediaImpact: "18710",
    Followers: "6119",
    Engagement: "10994",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "OguzTAkpinar",
    MediaImpact: "17876",
    Followers: "1327",
    Engagement: "15239",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "trtworldforum",
    MediaImpact: "15974",
    Followers: "14046",
    Engagement: "1911",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "CGI_Istanbul",
    MediaImpact: "15825",
    Followers: "11276",
    Engagement: "4360",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "akifsarier",
    MediaImpact: "15351",
    Followers: "579",
    Engagement: "14395",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "nirmak",
    MediaImpact: "14982",
    Followers: "582",
    Engagement: "13969",
    Category: "Culture",
    CategoryAll: "All",
  },
  {
    Username: "kartalbusemerke",
    MediaImpact: "14195",
    Followers: "9215",
    Engagement: "4763",
    Category: "General",
    CategoryAll: "All",
  },
  {
    Username: "mcenzura",
    MediaImpact: "13343",
    Followers: "381",
    Engagement: "12676",
    Category: "General",
    CategoryAll: "All",
  },
];
