export const data = [
  {
    Datetime: "10/06/2022",
    Event:
      "Once a safe haven, Iranians in Turkey say civil liberties are at risk",
    URL: "https://www.al-monitor.com/originals/2022/10/once-safe-haven-iranians-turkey-say-civil-liberties-are-risk",
    Category: "Lifestyle",
    Sentiment_Category: "Positive",
    Username: "Al-Monitor",
    CategoryAll: "All",
  },
  {
    Datetime: "10/06/2022",
    Event:
      "When Hate Becomes an Instrument: 4 Queer Culture Workers From Turkey Respond to the Anti-LGBT+ Rally in Istanbul",
    URL: "https://news.artnet.com/art-world/when-hate-becomes-an-instrument-4-queer-culture-workers-from-turkey-respond-to-the-anti-lgbt-rally-in-istanbul-2187477",
    Category: "Culture",
    Sentiment_Category: "Negative",
    Username: "Artnet News",
    CategoryAll: "All",
  },
  {
    Datetime: "10/06/2022",
    Event: "Ten most popular street foods you shouldn’t miss in Istanbul",
    URL: "https://thepeninsulaqatar.com/article/06/10/2022/ten-most-popular-street-foods-you-shouldnt-miss-in-istanbul",
    Category: "Culture",
    Sentiment_Category: "Positive",
    Username: "The Peninsula Qatar",
    CategoryAll: "All",
  },
  {
    Datetime: "10/20/2022",
    Event:
      "Bengaluru-bound Lufthansa flight diverted to Istanbul; '31 hours later - no hotel, no staff,' claims Grammy winner Ricky Kej",
    URL: "https://www.msn.com/en-in/lifestyle/travel/bengaluru-bound-lufthansa-flight-diverted-to-istanbul-31-hours-later-no-hotel-no-staff-claims-grammy-winner-ricky-kej/ar-AA13a2g7",
    Category: "Lifestyle",
    Sentiment_Category: "Negative",
    Username: "MSN",
    CategoryAll: "All",
  },
  {
    Datetime: "10/20/2022",
    Event:
      "‘I feel dumb and ashamed’: Woman slams Istanbul Airport for not stocking a single menstrual product",
    URL: "https://www.msn.com/en-gb/lifestyle/travel/i-feel-dumb-and-ashamed-woman-slams-istanbul-airport-for-not-stocking-a-single-menstrual-product/ar-AA13607h",
    Category: "Lifestyle",
    Sentiment_Category: "Negative",
    Username: "MSN",
    CategoryAll: "All",
  },
  {
    Datetime: "10/20/2022",
    Event: "The best free economic zones for buying real estate in Istanbul",
    URL: "https://www.luxurytravelmagazine.com/news-articles/the-best-free-economic-zones-for-buying-real-estate-in-istanbul",
    Category: "Economics",
    Sentiment_Category: "Positive",
    Username: "Luxury Travel Magazine",
    CategoryAll: "All",
  },
  {
    Datetime: "10/20/2022",
    Event: "Meet Fatih Tutak, Turkey's first 2-Michelin Star chef in Istanbul",
    URL: "https://www.euronews.com/culture/2022/10/17/meet-fatih-tutak-turkeys-first-2-michelin-star-chef-in-istanbul",
    Category: "Culture",
    Sentiment_Category: "Positive",
    Username: "Euronews",
    CategoryAll: "All",
  },
  {
    Datetime: "10/21/2022",
    Event:
      "Indian market is important to us, says Turkish Airlines CEO Bilal Eksi",
    URL: "https://www.business-standard.com/article/companies/india-is-important-to-us-turkish-airlines-ceo-bilal-ek%C5%9Fi-122102001028_1.html",
    Category: "Traffic",
    Sentiment_Category: "Positive",
    Username: "Business Standard",
    CategoryAll: "All",
  },
  {
    Datetime: "10/22/2022",
    Event:
      "Rhinoplasty in Turkey explained - why clinics in Istanbul are so popular",
    URL: "https://www.lincolnshirelive.co.uk/special-features/rhinoplasty-turkey-explained-clinics-istanbul-7713075",
    Category: "Education",
    Sentiment_Category: "Positive",
    Username: "Lincolnshire Live",
    CategoryAll: "All",
  },
  {
    Datetime: "10/22/2022",
    Event:
      "Assassinated journalist Musa Anter's family applies to top court following dismissal of case",
    URL: "https://m.bianet.org/english/law/268853-assassinated-journalist-musa-anter-s-family-applies-to-top-court-following-dismissal-of-case",
    Category: "Culture",
    Sentiment_Category: "Positive",
    Username: "Bianet",
    CategoryAll: "All",
  },
  {
    Datetime: "10/24/2022",
    Event: "Be good ambassadors, top Mandera girls studying in Turkey urged",
    URL: "https://www.the-star.co.ke/counties/north-eastern/2022-10-23-be-good-ambassadors-top-mandera-girls-studying-in-turkey-urged/",
    Category: "Education",
    Sentiment_Category: "Positive",
    Username: "The Star",
    CategoryAll: "All",
  },
  {
    Datetime: "10/25/2022",
    Event:
      "Axe falls on Japan’s economy minister over links to controversial Unification Church",
    URL: "https://www.aa.com.tr/en/asia-pacific/axe-falls-on-japan-s-economy-minister-over-links-to-controversial-unification-church/2720029",
    Category: "Economics",
    Sentiment_Category: "Positive",
    Username: "Anadolu Agency",
    CategoryAll: "All",
  },
  {
    Datetime: "10/25/2022",
    Event: "Sweet temptation: Istanbul's beloved 'brothel dessert'",
    URL: "https://www.bbc.com/travel/article/20221024-sweet-temptation-istanbuls-beloved-brothel-dessert",
    Category: "Culture",
    Sentiment_Category: "Positive",
    Username: "BBC",
    CategoryAll: "All",
  },
  {
    Datetime: "10/26/2022",
    Event: "‘Basically a Savior’: Why Crypto Is So Popular in Turkey",
    URL: "https://finance.yahoo.com/news/basically-savior-why-crypto-popular-184554952.html",
    Category: "Government",
    Sentiment_Category: "Positive",
    Username: "Yahoo Finance",
    CategoryAll: "All",
  },
  {
    Datetime: "10/26/2022",
    Event:
      "Biden called Turkish PM to warn of false accusations against the US, but Turkey remained unmoved",
    URL: "https://nordicmonitor.com/2022/10/biden-called-turkish-pm-to-warn-false-accusations-against-the-us-turkey-unmoved/",
    Category: "Government",
    Sentiment_Category: "Negative",
    Username: "Nordic Monitor",
    CategoryAll: "All",
  },
  {
    Datetime: "10/26/2022",
    Event:
      "Greece should see Türkiye as strong, reliable partner, not threat: Akar",
    URL: "https://www.dailysabah.com/politics/eu-affairs/greece-should-see-turkiye-as-strong-reliable-partner-not-threat-akar",
    Category: "Education",
    Sentiment_Category: "Positive",
    Username: "Daily Sabah",
    CategoryAll: "All",
  },
  {
    Datetime: "10/26/2022",
    Event:
      "TAV Havalimanlari : 26.10.2022, TAV announces EUR 753M revenue in the first nine months",
    URL: "https://www.marketscreener.com/quote/stock/TAV-HAVALIMANLARI-HOLDING-6499546/news/TAV-Havalimanlari-26-10-2022-TAV-announces-EUR-753M-revenue-in-the-first-nine-months-42095934/",
    Category: "Economics",
    Sentiment_Category: "Positive",
    Username: "MarketScreener",
    CategoryAll: "All",
  },
];
