export const SET_FILTERS = "SET_FILTERS";
export const UPDATE_LOADERS = "UPDATE_LOADERS";
export const UPDATE_ALL_LOADERS_TRUE = "UPDATE_ALL_LOADERS_TRUE";
export const RESET_FILTERS = "RESET_FILTERS";
export const TOGGLE_CALENDER = "TOGGLE_CALENDER";
export const CLOSE_CALENDER = "CLOSE_CALENDER";
export const SET_DROP_DATA = "SET_DROP_DATA";
export const SET_LOADERS = "SET_LOADERS";
